### ISSUE TITLE
cssnano is discarding sourcemap comment

### ISSUE THREAD

**Issue by corysimmons** [ben-eb/postcss-discard-comments#10]
I'm using clean-css to get rid of repeated selectors, and cssnano to minify.

clean css adds a sourcemap.

![image](https://cloud.githubusercontent.com/assets/224636/12870873/281b7c50-cd27-11e5-881d-e5e549ed96b0.png)

cssnano removes it

![image](https://cloud.githubusercontent.com/assets/224636/12870875/3660e93a-cd27-11e5-9a27-96165279e8db.png)

I've even tried this with the `--no-discardComments` feature in the CLI and it still removes the sourcemap comment, so I'm not even sure if this is the right place to open this issue...

**Comment by ben-eb** [comment]
Sourcemaps are handled by PostCSS, you'll need to configure those.

https://github.com/postcss/postcss/blob/master/docs/source-maps.md

**Comment by corysimmons** [comment]
Why is cssnano discarding _any_ comments whatsoever...?

**Comment by ben-eb** [comment]
It's not cssnano that does it, PostCSS takes care of sourcemaps. I have no control over their removal with this plugin. The documentation wasn't clear on that so I have updated it.

https://github.com/ben-eb/postcss-discard-comments#output

**Comment by corysimmons** [comment]
Alright thanks for updating docs. :+1:
