### ISSUE TITLE
Add an option removeOnly

### ISSUE THREAD

**Issue by dmitrykiselyov** [ben-eb/postcss-discard-comments#3]
Thank you for the plugin :+1: 

It would be nice to see an option **removeOnly**.
Remove all comments marked as for example `/*- */` with the ability to change it.

```css
/*- Remove */

/* Leave */
```

Mark all comment with `!` just to remove a few is a little bit annoying.

**Comment by ben-eb** [comment]
I think I would prefer a user-defined function, `remove` where you return `true` to remove and `false` to keep. Would appreciate a pull request for this, if not I'll have a look when I can. :+1:

**Comment by dmitrykiselyov** [comment]
Ok, I will try.

**Comment by dmitrykiselyov** [comment]
`remove: false` Keep all regular comments
`removeAll` Remove all comments marked as important
But what if I want to keep some comments marked as important? :smile: 
For example `/*! normalize.css */`

**Comment by ben-eb** [comment]
A user supplied function would override those options.

**Comment by dmitrykiselyov** [comment]
It would be better that you implement it when you find the time :wink:

**Comment by dmitrykiselyov** [comment]
Do you mean something like this?

**config**
```js
remove: function(comment) { return comment.indexOf('@') == 0; }
```

**commentRemover.js**
```js
CommentRemover.prototype.canRemove = function (comment) {
    var remove = this.options.remove;
    if (remove) {      
        return remove(comment);
    } else { 
        var isImportant = comment.indexOf('!') === 0;
        if (!isImportant && comment.indexOf('#') !== 0) {
            return true;
        } else if (isImportant) {
            if (this.options.removeAll || this._hasFirst) {
                return true;
            } else if (this.options.removeAllButFirst && !this._hasFirst) {
                this._hasFirst = true;
                return false;
            }
        }
    }
};
```

**Comment by ben-eb** [comment]
Yep. It would need tests too.

**Comment by ben-eb** [comment]
https://github.com/ben-eb/postcss-discard-comments/commit/14abc58da293ba6fdc52a5830b049a25378c0272
