### ISSUE TITLE
Also discards spaces

### ISSUE THREAD

**Issue by dustindowell22** [ben-eb/postcss-discard-comments#37]
in
```
.foo {
  margin: 0;
}
```

out
```
.foo {
  margin:0;
}
```

I'm trying to clean up some files but I want to keep spaces between the colon and the values.

**Comment by ben-eb** [comment]
This is probably avoidable but I don't want to put any logic in that conditionally removes spaces; the main use case for this tool is CSS compression. What might be good to do however is to run this output through a CSS formatter, which gives you more options to format your CSS how you would like.

* https://github.com/ben-eb/perfectionist
* https://github.com/morishitter/stylefmt
