### ISSUE TITLE
removeAllButFirst keeps the first !comment only once

### ISSUE THREAD

**Issue by dmitrykiselyov** [ben-eb/postcss-discard-comments#4]
`removeAllButFirst: true` keeps the first `!comment` only once
I use [brunch](https://github.com/brunch/brunch)

**Comment by ben-eb** [comment]
I think this is to do with the initialisation of the comment remover outside of the function that is returned to PostCSS - so it will only work on the first file. I'll fix it after your other patch. :smile:

**Comment by dmitrykiselyov** [comment]
:+1:
